/// Flutter icons WeatherIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WeatherIcons
///      fonts:
///       - asset: fonts/WeatherIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WeatherIcons {
  WeatherIcons._();

  static const _kFontFam = 'WeatherIcons';
  static const String? _kFontPkg = null;

  static const IconData thunderstorm_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wind_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broken_clouds = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear_sky_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData few_clouds_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mist_icon = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moisture_icon = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain_icon = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scattered_clouds_icon = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shower_rain_icon = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snow_icon = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
